export const CATEGORY_DOMAINS = {
  Technology: [
    "Artificial Intelligence",
    "Software Development",
    "Cybersecurity",
    "Blockchain & Crypto",
    "Robotics",
    "Consumer Electronics",
    "VR/AR & Metaverse",
    "Internet Culture",
    "Future Tech",
    "Data Science",
  ],
  Science: [
    "Space Exploration",
    "Neuroscience",
    "Climate Change",
    "Biotechnology",
    "Physics",
    "Renewable Energy",
    "Astronomy",
    "Genetics",
    "Marine Biology",
    "Evolution",
  ],
  Business: [
    "Global Economy",
    "Startups & VC",
    "Personal Finance",
    "Marketing & Branding",
    "Leadership",
    "Stock Market",
    "Real Estate",
    "E-commerce",
    "Business Strategy",
    "Productivity",
  ],
  Society: [
    "World History",
    "Politics",
    "Culture & Society",
    "Philosophy",
    "Sociology",
    "Law & Justice",
    "Urban Planning",
    "Education",
    "Anthropology",
    "Religion & Mythology",
  ],
  Lifestyle: [
    "Health & Wellness",
    "Mental Health",
    "Travel & Adventure",
    "Interior Design",
    "Fashion & Style",
    "Food & Cooking",
    "Fitness",
    "Self Improvement",
    "Relationships",
    "Minimalism",
  ],
  Arts: [
    "Modern Art",
    "Film Analysis",
    "Music Theory",
    "Architecture",
    "Photography",
    "Literature",
    "Design History",
    "Theater",
    "Creative Writing",
    "Digital Art",
  ],
  Entertainment: [
    "Movies & TV",
    "Video Games",
    "Music Trends",
    "Celebrity News",
    "Sports Analysis",
    "Esports",
    "Comics & Manga",
    "Streaming Culture",
  ],
} as const;

// Flattened list for AI prompt
export const ALL_CATEGORIES = Object.values(CATEGORY_DOMAINS).flat();

export type CategoryDomain = keyof typeof CATEGORY_DOMAINS;
export type Category = (typeof ALL_CATEGORIES)[number];
